// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmqqltkvtayvzelcbavu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcXFsdGt2dGF5dnplbGNiYXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NDI1MTUsImV4cCI6MjA1NTQxODUxNX0.e5F6PJEotL-kUjNox8fP1JNpIoyO2dsdj0_fNVHCwSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);